/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WarehouseWarehouseLayoutRouteImport } from './routes/warehouse/_WarehouseLayout'
import { Route as OperationsOperationsLayoutRouteImport } from './routes/operations/_OperationsLayout'
import { Route as OperationsOperationsLayoutIndexRouteImport } from './routes/operations/_OperationsLayout/index'
import { Route as OperationsOperationsLayoutProfileRouteImport } from './routes/operations/_OperationsLayout/profile'
import { Route as WarehouseWarehouseLayoutWarehousesIndexRouteImport } from './routes/warehouse/_WarehouseLayout/warehouses/index'
import { Route as WarehouseWarehouseLayoutSuppliersIndexRouteImport } from './routes/warehouse/_WarehouseLayout/suppliers/index'
import { Route as WarehouseWarehouseLayoutStockTransfersIndexRouteImport } from './routes/warehouse/_WarehouseLayout/stock-transfers/index'
import { Route as WarehouseWarehouseLayoutReceiptsIndexRouteImport } from './routes/warehouse/_WarehouseLayout/receipts/index'
import { Route as WarehouseWarehouseLayoutQuotesIndexRouteImport } from './routes/warehouse/_WarehouseLayout/quotes/index'
import { Route as WarehouseWarehouseLayoutPurchasesIndexRouteImport } from './routes/warehouse/_WarehouseLayout/purchases/index'
import { Route as WarehouseWarehouseLayoutProfileIndexRouteImport } from './routes/warehouse/_WarehouseLayout/profile/index'
import { Route as WarehouseWarehouseLayoutLocationsIndexRouteImport } from './routes/warehouse/_WarehouseLayout/locations/index'
import { Route as WarehouseWarehouseLayoutItemsIndexRouteImport } from './routes/warehouse/_WarehouseLayout/items/index'
import { Route as WarehouseWarehouseLayoutDisposalsIndexRouteImport } from './routes/warehouse/_WarehouseLayout/disposals/index'
import { Route as WarehouseWarehouseLayoutDashboardIndexRouteImport } from './routes/warehouse/_WarehouseLayout/dashboard/index'
import { Route as WarehouseWarehouseLayoutCustomersIndexRouteImport } from './routes/warehouse/_WarehouseLayout/customers/index'
import { Route as WarehouseWarehouseLayoutContainersIndexRouteImport } from './routes/warehouse/_WarehouseLayout/containers/index'
import { Route as WarehouseWarehouseLayoutCategoriesIndexRouteImport } from './routes/warehouse/_WarehouseLayout/categories/index'
import { Route as WarehouseWarehouseLayoutAssignmentsIndexRouteImport } from './routes/warehouse/_WarehouseLayout/assignments/index'
import { Route as WarehouseWarehouseLayoutWarehousesInfoIdRouteImport } from './routes/warehouse/_WarehouseLayout/warehouses/info/$id'
import { Route as WarehouseWarehouseLayoutItemsInfoIdRouteImport } from './routes/warehouse/_WarehouseLayout/items/info/$id'
import { Route as WarehouseWarehouseLayoutCustomersInfoIdRouteImport } from './routes/warehouse/_WarehouseLayout/customers/info/$id'

const WarehouseRouteImport = createFileRoute('/warehouse')()
const OperationsRouteImport = createFileRoute('/operations')()
const UnauthorizedLazyRouteImport = createFileRoute('/unauthorized')()

const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedLazyRoute = UnauthorizedLazyRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/unauthorized.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseWarehouseLayoutRoute =
  WarehouseWarehouseLayoutRouteImport.update({
    id: '/_WarehouseLayout',
    getParentRoute: () => WarehouseRoute,
  } as any)
const OperationsOperationsLayoutRoute =
  OperationsOperationsLayoutRouteImport.update({
    id: '/_OperationsLayout',
    getParentRoute: () => OperationsRoute,
  } as any)
const OperationsOperationsLayoutIndexRoute =
  OperationsOperationsLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OperationsOperationsLayoutRoute,
  } as any)
const OperationsOperationsLayoutProfileRoute =
  OperationsOperationsLayoutProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => OperationsOperationsLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutWarehousesIndexRoute =
  WarehouseWarehouseLayoutWarehousesIndexRouteImport.update({
    id: '/warehouses/',
    path: '/warehouses/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutSuppliersIndexRoute =
  WarehouseWarehouseLayoutSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutStockTransfersIndexRoute =
  WarehouseWarehouseLayoutStockTransfersIndexRouteImport.update({
    id: '/stock-transfers/',
    path: '/stock-transfers/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutReceiptsIndexRoute =
  WarehouseWarehouseLayoutReceiptsIndexRouteImport.update({
    id: '/receipts/',
    path: '/receipts/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutQuotesIndexRoute =
  WarehouseWarehouseLayoutQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutPurchasesIndexRoute =
  WarehouseWarehouseLayoutPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutProfileIndexRoute =
  WarehouseWarehouseLayoutProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutLocationsIndexRoute =
  WarehouseWarehouseLayoutLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutItemsIndexRoute =
  WarehouseWarehouseLayoutItemsIndexRouteImport.update({
    id: '/items/',
    path: '/items/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutDisposalsIndexRoute =
  WarehouseWarehouseLayoutDisposalsIndexRouteImport.update({
    id: '/disposals/',
    path: '/disposals/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutDashboardIndexRoute =
  WarehouseWarehouseLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutCustomersIndexRoute =
  WarehouseWarehouseLayoutCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutContainersIndexRoute =
  WarehouseWarehouseLayoutContainersIndexRouteImport.update({
    id: '/containers/',
    path: '/containers/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutCategoriesIndexRoute =
  WarehouseWarehouseLayoutCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutAssignmentsIndexRoute =
  WarehouseWarehouseLayoutAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutWarehousesInfoIdRoute =
  WarehouseWarehouseLayoutWarehousesInfoIdRouteImport.update({
    id: '/warehouses/info/$id',
    path: '/warehouses/info/$id',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutItemsInfoIdRoute =
  WarehouseWarehouseLayoutItemsInfoIdRouteImport.update({
    id: '/items/info/$id',
    path: '/items/info/$id',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)
const WarehouseWarehouseLayoutCustomersInfoIdRoute =
  WarehouseWarehouseLayoutCustomersInfoIdRouteImport.update({
    id: '/customers/info/$id',
    path: '/customers/info/$id',
    getParentRoute: () => WarehouseWarehouseLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedLazyRoute
  '/operations': typeof OperationsOperationsLayoutRouteWithChildren
  '/warehouse': typeof WarehouseWarehouseLayoutRouteWithChildren
  '/operations/profile': typeof OperationsOperationsLayoutProfileRoute
  '/operations/': typeof OperationsOperationsLayoutIndexRoute
  '/warehouse/assignments': typeof WarehouseWarehouseLayoutAssignmentsIndexRoute
  '/warehouse/categories': typeof WarehouseWarehouseLayoutCategoriesIndexRoute
  '/warehouse/containers': typeof WarehouseWarehouseLayoutContainersIndexRoute
  '/warehouse/customers': typeof WarehouseWarehouseLayoutCustomersIndexRoute
  '/warehouse/dashboard': typeof WarehouseWarehouseLayoutDashboardIndexRoute
  '/warehouse/disposals': typeof WarehouseWarehouseLayoutDisposalsIndexRoute
  '/warehouse/items': typeof WarehouseWarehouseLayoutItemsIndexRoute
  '/warehouse/locations': typeof WarehouseWarehouseLayoutLocationsIndexRoute
  '/warehouse/profile': typeof WarehouseWarehouseLayoutProfileIndexRoute
  '/warehouse/purchases': typeof WarehouseWarehouseLayoutPurchasesIndexRoute
  '/warehouse/quotes': typeof WarehouseWarehouseLayoutQuotesIndexRoute
  '/warehouse/receipts': typeof WarehouseWarehouseLayoutReceiptsIndexRoute
  '/warehouse/stock-transfers': typeof WarehouseWarehouseLayoutStockTransfersIndexRoute
  '/warehouse/suppliers': typeof WarehouseWarehouseLayoutSuppliersIndexRoute
  '/warehouse/warehouses': typeof WarehouseWarehouseLayoutWarehousesIndexRoute
  '/warehouse/customers/info/$id': typeof WarehouseWarehouseLayoutCustomersInfoIdRoute
  '/warehouse/items/info/$id': typeof WarehouseWarehouseLayoutItemsInfoIdRoute
  '/warehouse/warehouses/info/$id': typeof WarehouseWarehouseLayoutWarehousesInfoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedLazyRoute
  '/operations': typeof OperationsOperationsLayoutIndexRoute
  '/warehouse': typeof WarehouseWarehouseLayoutRouteWithChildren
  '/operations/profile': typeof OperationsOperationsLayoutProfileRoute
  '/warehouse/assignments': typeof WarehouseWarehouseLayoutAssignmentsIndexRoute
  '/warehouse/categories': typeof WarehouseWarehouseLayoutCategoriesIndexRoute
  '/warehouse/containers': typeof WarehouseWarehouseLayoutContainersIndexRoute
  '/warehouse/customers': typeof WarehouseWarehouseLayoutCustomersIndexRoute
  '/warehouse/dashboard': typeof WarehouseWarehouseLayoutDashboardIndexRoute
  '/warehouse/disposals': typeof WarehouseWarehouseLayoutDisposalsIndexRoute
  '/warehouse/items': typeof WarehouseWarehouseLayoutItemsIndexRoute
  '/warehouse/locations': typeof WarehouseWarehouseLayoutLocationsIndexRoute
  '/warehouse/profile': typeof WarehouseWarehouseLayoutProfileIndexRoute
  '/warehouse/purchases': typeof WarehouseWarehouseLayoutPurchasesIndexRoute
  '/warehouse/quotes': typeof WarehouseWarehouseLayoutQuotesIndexRoute
  '/warehouse/receipts': typeof WarehouseWarehouseLayoutReceiptsIndexRoute
  '/warehouse/stock-transfers': typeof WarehouseWarehouseLayoutStockTransfersIndexRoute
  '/warehouse/suppliers': typeof WarehouseWarehouseLayoutSuppliersIndexRoute
  '/warehouse/warehouses': typeof WarehouseWarehouseLayoutWarehousesIndexRoute
  '/warehouse/customers/info/$id': typeof WarehouseWarehouseLayoutCustomersInfoIdRoute
  '/warehouse/items/info/$id': typeof WarehouseWarehouseLayoutItemsInfoIdRoute
  '/warehouse/warehouses/info/$id': typeof WarehouseWarehouseLayoutWarehousesInfoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedLazyRoute
  '/operations': typeof OperationsRouteWithChildren
  '/operations/_OperationsLayout': typeof OperationsOperationsLayoutRouteWithChildren
  '/warehouse': typeof WarehouseRouteWithChildren
  '/warehouse/_WarehouseLayout': typeof WarehouseWarehouseLayoutRouteWithChildren
  '/operations/_OperationsLayout/profile': typeof OperationsOperationsLayoutProfileRoute
  '/operations/_OperationsLayout/': typeof OperationsOperationsLayoutIndexRoute
  '/warehouse/_WarehouseLayout/assignments/': typeof WarehouseWarehouseLayoutAssignmentsIndexRoute
  '/warehouse/_WarehouseLayout/categories/': typeof WarehouseWarehouseLayoutCategoriesIndexRoute
  '/warehouse/_WarehouseLayout/containers/': typeof WarehouseWarehouseLayoutContainersIndexRoute
  '/warehouse/_WarehouseLayout/customers/': typeof WarehouseWarehouseLayoutCustomersIndexRoute
  '/warehouse/_WarehouseLayout/dashboard/': typeof WarehouseWarehouseLayoutDashboardIndexRoute
  '/warehouse/_WarehouseLayout/disposals/': typeof WarehouseWarehouseLayoutDisposalsIndexRoute
  '/warehouse/_WarehouseLayout/items/': typeof WarehouseWarehouseLayoutItemsIndexRoute
  '/warehouse/_WarehouseLayout/locations/': typeof WarehouseWarehouseLayoutLocationsIndexRoute
  '/warehouse/_WarehouseLayout/profile/': typeof WarehouseWarehouseLayoutProfileIndexRoute
  '/warehouse/_WarehouseLayout/purchases/': typeof WarehouseWarehouseLayoutPurchasesIndexRoute
  '/warehouse/_WarehouseLayout/quotes/': typeof WarehouseWarehouseLayoutQuotesIndexRoute
  '/warehouse/_WarehouseLayout/receipts/': typeof WarehouseWarehouseLayoutReceiptsIndexRoute
  '/warehouse/_WarehouseLayout/stock-transfers/': typeof WarehouseWarehouseLayoutStockTransfersIndexRoute
  '/warehouse/_WarehouseLayout/suppliers/': typeof WarehouseWarehouseLayoutSuppliersIndexRoute
  '/warehouse/_WarehouseLayout/warehouses/': typeof WarehouseWarehouseLayoutWarehousesIndexRoute
  '/warehouse/_WarehouseLayout/customers/info/$id': typeof WarehouseWarehouseLayoutCustomersInfoIdRoute
  '/warehouse/_WarehouseLayout/items/info/$id': typeof WarehouseWarehouseLayoutItemsInfoIdRoute
  '/warehouse/_WarehouseLayout/warehouses/info/$id': typeof WarehouseWarehouseLayoutWarehousesInfoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/operations'
    | '/warehouse'
    | '/operations/profile'
    | '/operations/'
    | '/warehouse/assignments'
    | '/warehouse/categories'
    | '/warehouse/containers'
    | '/warehouse/customers'
    | '/warehouse/dashboard'
    | '/warehouse/disposals'
    | '/warehouse/items'
    | '/warehouse/locations'
    | '/warehouse/profile'
    | '/warehouse/purchases'
    | '/warehouse/quotes'
    | '/warehouse/receipts'
    | '/warehouse/stock-transfers'
    | '/warehouse/suppliers'
    | '/warehouse/warehouses'
    | '/warehouse/customers/info/$id'
    | '/warehouse/items/info/$id'
    | '/warehouse/warehouses/info/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/operations'
    | '/warehouse'
    | '/operations/profile'
    | '/warehouse/assignments'
    | '/warehouse/categories'
    | '/warehouse/containers'
    | '/warehouse/customers'
    | '/warehouse/dashboard'
    | '/warehouse/disposals'
    | '/warehouse/items'
    | '/warehouse/locations'
    | '/warehouse/profile'
    | '/warehouse/purchases'
    | '/warehouse/quotes'
    | '/warehouse/receipts'
    | '/warehouse/stock-transfers'
    | '/warehouse/suppliers'
    | '/warehouse/warehouses'
    | '/warehouse/customers/info/$id'
    | '/warehouse/items/info/$id'
    | '/warehouse/warehouses/info/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/unauthorized'
    | '/operations'
    | '/operations/_OperationsLayout'
    | '/warehouse'
    | '/warehouse/_WarehouseLayout'
    | '/operations/_OperationsLayout/profile'
    | '/operations/_OperationsLayout/'
    | '/warehouse/_WarehouseLayout/assignments/'
    | '/warehouse/_WarehouseLayout/categories/'
    | '/warehouse/_WarehouseLayout/containers/'
    | '/warehouse/_WarehouseLayout/customers/'
    | '/warehouse/_WarehouseLayout/dashboard/'
    | '/warehouse/_WarehouseLayout/disposals/'
    | '/warehouse/_WarehouseLayout/items/'
    | '/warehouse/_WarehouseLayout/locations/'
    | '/warehouse/_WarehouseLayout/profile/'
    | '/warehouse/_WarehouseLayout/purchases/'
    | '/warehouse/_WarehouseLayout/quotes/'
    | '/warehouse/_WarehouseLayout/receipts/'
    | '/warehouse/_WarehouseLayout/stock-transfers/'
    | '/warehouse/_WarehouseLayout/suppliers/'
    | '/warehouse/_WarehouseLayout/warehouses/'
    | '/warehouse/_WarehouseLayout/customers/info/$id'
    | '/warehouse/_WarehouseLayout/items/info/$id'
    | '/warehouse/_WarehouseLayout/warehouses/info/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedLazyRoute: typeof UnauthorizedLazyRoute
  OperationsRoute: typeof OperationsRouteWithChildren
  WarehouseRoute: typeof WarehouseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/_WarehouseLayout': {
      id: '/warehouse/_WarehouseLayout'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseWarehouseLayoutRouteImport
      parentRoute: typeof WarehouseRoute
    }
    '/operations/_OperationsLayout': {
      id: '/operations/_OperationsLayout'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsOperationsLayoutRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/_OperationsLayout/': {
      id: '/operations/_OperationsLayout/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsOperationsLayoutIndexRouteImport
      parentRoute: typeof OperationsOperationsLayoutRoute
    }
    '/operations/_OperationsLayout/profile': {
      id: '/operations/_OperationsLayout/profile'
      path: '/profile'
      fullPath: '/operations/profile'
      preLoaderRoute: typeof OperationsOperationsLayoutProfileRouteImport
      parentRoute: typeof OperationsOperationsLayoutRoute
    }
    '/warehouse/_WarehouseLayout/warehouses/': {
      id: '/warehouse/_WarehouseLayout/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouse/warehouses'
      preLoaderRoute: typeof WarehouseWarehouseLayoutWarehousesIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/suppliers/': {
      id: '/warehouse/_WarehouseLayout/suppliers/'
      path: '/suppliers'
      fullPath: '/warehouse/suppliers'
      preLoaderRoute: typeof WarehouseWarehouseLayoutSuppliersIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/stock-transfers/': {
      id: '/warehouse/_WarehouseLayout/stock-transfers/'
      path: '/stock-transfers'
      fullPath: '/warehouse/stock-transfers'
      preLoaderRoute: typeof WarehouseWarehouseLayoutStockTransfersIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/receipts/': {
      id: '/warehouse/_WarehouseLayout/receipts/'
      path: '/receipts'
      fullPath: '/warehouse/receipts'
      preLoaderRoute: typeof WarehouseWarehouseLayoutReceiptsIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/quotes/': {
      id: '/warehouse/_WarehouseLayout/quotes/'
      path: '/quotes'
      fullPath: '/warehouse/quotes'
      preLoaderRoute: typeof WarehouseWarehouseLayoutQuotesIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/purchases/': {
      id: '/warehouse/_WarehouseLayout/purchases/'
      path: '/purchases'
      fullPath: '/warehouse/purchases'
      preLoaderRoute: typeof WarehouseWarehouseLayoutPurchasesIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/profile/': {
      id: '/warehouse/_WarehouseLayout/profile/'
      path: '/profile'
      fullPath: '/warehouse/profile'
      preLoaderRoute: typeof WarehouseWarehouseLayoutProfileIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/locations/': {
      id: '/warehouse/_WarehouseLayout/locations/'
      path: '/locations'
      fullPath: '/warehouse/locations'
      preLoaderRoute: typeof WarehouseWarehouseLayoutLocationsIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/items/': {
      id: '/warehouse/_WarehouseLayout/items/'
      path: '/items'
      fullPath: '/warehouse/items'
      preLoaderRoute: typeof WarehouseWarehouseLayoutItemsIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/disposals/': {
      id: '/warehouse/_WarehouseLayout/disposals/'
      path: '/disposals'
      fullPath: '/warehouse/disposals'
      preLoaderRoute: typeof WarehouseWarehouseLayoutDisposalsIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/dashboard/': {
      id: '/warehouse/_WarehouseLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/warehouse/dashboard'
      preLoaderRoute: typeof WarehouseWarehouseLayoutDashboardIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/customers/': {
      id: '/warehouse/_WarehouseLayout/customers/'
      path: '/customers'
      fullPath: '/warehouse/customers'
      preLoaderRoute: typeof WarehouseWarehouseLayoutCustomersIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/containers/': {
      id: '/warehouse/_WarehouseLayout/containers/'
      path: '/containers'
      fullPath: '/warehouse/containers'
      preLoaderRoute: typeof WarehouseWarehouseLayoutContainersIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/categories/': {
      id: '/warehouse/_WarehouseLayout/categories/'
      path: '/categories'
      fullPath: '/warehouse/categories'
      preLoaderRoute: typeof WarehouseWarehouseLayoutCategoriesIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/assignments/': {
      id: '/warehouse/_WarehouseLayout/assignments/'
      path: '/assignments'
      fullPath: '/warehouse/assignments'
      preLoaderRoute: typeof WarehouseWarehouseLayoutAssignmentsIndexRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/warehouses/info/$id': {
      id: '/warehouse/_WarehouseLayout/warehouses/info/$id'
      path: '/warehouses/info/$id'
      fullPath: '/warehouse/warehouses/info/$id'
      preLoaderRoute: typeof WarehouseWarehouseLayoutWarehousesInfoIdRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/items/info/$id': {
      id: '/warehouse/_WarehouseLayout/items/info/$id'
      path: '/items/info/$id'
      fullPath: '/warehouse/items/info/$id'
      preLoaderRoute: typeof WarehouseWarehouseLayoutItemsInfoIdRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
    '/warehouse/_WarehouseLayout/customers/info/$id': {
      id: '/warehouse/_WarehouseLayout/customers/info/$id'
      path: '/customers/info/$id'
      fullPath: '/warehouse/customers/info/$id'
      preLoaderRoute: typeof WarehouseWarehouseLayoutCustomersInfoIdRouteImport
      parentRoute: typeof WarehouseWarehouseLayoutRoute
    }
  }
}

interface OperationsOperationsLayoutRouteChildren {
  OperationsOperationsLayoutProfileRoute: typeof OperationsOperationsLayoutProfileRoute
  OperationsOperationsLayoutIndexRoute: typeof OperationsOperationsLayoutIndexRoute
}

const OperationsOperationsLayoutRouteChildren: OperationsOperationsLayoutRouteChildren =
  {
    OperationsOperationsLayoutProfileRoute:
      OperationsOperationsLayoutProfileRoute,
    OperationsOperationsLayoutIndexRoute: OperationsOperationsLayoutIndexRoute,
  }

const OperationsOperationsLayoutRouteWithChildren =
  OperationsOperationsLayoutRoute._addFileChildren(
    OperationsOperationsLayoutRouteChildren,
  )

interface OperationsRouteChildren {
  OperationsOperationsLayoutRoute: typeof OperationsOperationsLayoutRouteWithChildren
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsOperationsLayoutRoute: OperationsOperationsLayoutRouteWithChildren,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

interface WarehouseWarehouseLayoutRouteChildren {
  WarehouseWarehouseLayoutAssignmentsIndexRoute: typeof WarehouseWarehouseLayoutAssignmentsIndexRoute
  WarehouseWarehouseLayoutCategoriesIndexRoute: typeof WarehouseWarehouseLayoutCategoriesIndexRoute
  WarehouseWarehouseLayoutContainersIndexRoute: typeof WarehouseWarehouseLayoutContainersIndexRoute
  WarehouseWarehouseLayoutCustomersIndexRoute: typeof WarehouseWarehouseLayoutCustomersIndexRoute
  WarehouseWarehouseLayoutDashboardIndexRoute: typeof WarehouseWarehouseLayoutDashboardIndexRoute
  WarehouseWarehouseLayoutDisposalsIndexRoute: typeof WarehouseWarehouseLayoutDisposalsIndexRoute
  WarehouseWarehouseLayoutItemsIndexRoute: typeof WarehouseWarehouseLayoutItemsIndexRoute
  WarehouseWarehouseLayoutLocationsIndexRoute: typeof WarehouseWarehouseLayoutLocationsIndexRoute
  WarehouseWarehouseLayoutProfileIndexRoute: typeof WarehouseWarehouseLayoutProfileIndexRoute
  WarehouseWarehouseLayoutPurchasesIndexRoute: typeof WarehouseWarehouseLayoutPurchasesIndexRoute
  WarehouseWarehouseLayoutQuotesIndexRoute: typeof WarehouseWarehouseLayoutQuotesIndexRoute
  WarehouseWarehouseLayoutReceiptsIndexRoute: typeof WarehouseWarehouseLayoutReceiptsIndexRoute
  WarehouseWarehouseLayoutStockTransfersIndexRoute: typeof WarehouseWarehouseLayoutStockTransfersIndexRoute
  WarehouseWarehouseLayoutSuppliersIndexRoute: typeof WarehouseWarehouseLayoutSuppliersIndexRoute
  WarehouseWarehouseLayoutWarehousesIndexRoute: typeof WarehouseWarehouseLayoutWarehousesIndexRoute
  WarehouseWarehouseLayoutCustomersInfoIdRoute: typeof WarehouseWarehouseLayoutCustomersInfoIdRoute
  WarehouseWarehouseLayoutItemsInfoIdRoute: typeof WarehouseWarehouseLayoutItemsInfoIdRoute
  WarehouseWarehouseLayoutWarehousesInfoIdRoute: typeof WarehouseWarehouseLayoutWarehousesInfoIdRoute
}

const WarehouseWarehouseLayoutRouteChildren: WarehouseWarehouseLayoutRouteChildren =
  {
    WarehouseWarehouseLayoutAssignmentsIndexRoute:
      WarehouseWarehouseLayoutAssignmentsIndexRoute,
    WarehouseWarehouseLayoutCategoriesIndexRoute:
      WarehouseWarehouseLayoutCategoriesIndexRoute,
    WarehouseWarehouseLayoutContainersIndexRoute:
      WarehouseWarehouseLayoutContainersIndexRoute,
    WarehouseWarehouseLayoutCustomersIndexRoute:
      WarehouseWarehouseLayoutCustomersIndexRoute,
    WarehouseWarehouseLayoutDashboardIndexRoute:
      WarehouseWarehouseLayoutDashboardIndexRoute,
    WarehouseWarehouseLayoutDisposalsIndexRoute:
      WarehouseWarehouseLayoutDisposalsIndexRoute,
    WarehouseWarehouseLayoutItemsIndexRoute:
      WarehouseWarehouseLayoutItemsIndexRoute,
    WarehouseWarehouseLayoutLocationsIndexRoute:
      WarehouseWarehouseLayoutLocationsIndexRoute,
    WarehouseWarehouseLayoutProfileIndexRoute:
      WarehouseWarehouseLayoutProfileIndexRoute,
    WarehouseWarehouseLayoutPurchasesIndexRoute:
      WarehouseWarehouseLayoutPurchasesIndexRoute,
    WarehouseWarehouseLayoutQuotesIndexRoute:
      WarehouseWarehouseLayoutQuotesIndexRoute,
    WarehouseWarehouseLayoutReceiptsIndexRoute:
      WarehouseWarehouseLayoutReceiptsIndexRoute,
    WarehouseWarehouseLayoutStockTransfersIndexRoute:
      WarehouseWarehouseLayoutStockTransfersIndexRoute,
    WarehouseWarehouseLayoutSuppliersIndexRoute:
      WarehouseWarehouseLayoutSuppliersIndexRoute,
    WarehouseWarehouseLayoutWarehousesIndexRoute:
      WarehouseWarehouseLayoutWarehousesIndexRoute,
    WarehouseWarehouseLayoutCustomersInfoIdRoute:
      WarehouseWarehouseLayoutCustomersInfoIdRoute,
    WarehouseWarehouseLayoutItemsInfoIdRoute:
      WarehouseWarehouseLayoutItemsInfoIdRoute,
    WarehouseWarehouseLayoutWarehousesInfoIdRoute:
      WarehouseWarehouseLayoutWarehousesInfoIdRoute,
  }

const WarehouseWarehouseLayoutRouteWithChildren =
  WarehouseWarehouseLayoutRoute._addFileChildren(
    WarehouseWarehouseLayoutRouteChildren,
  )

interface WarehouseRouteChildren {
  WarehouseWarehouseLayoutRoute: typeof WarehouseWarehouseLayoutRouteWithChildren
}

const WarehouseRouteChildren: WarehouseRouteChildren = {
  WarehouseWarehouseLayoutRoute: WarehouseWarehouseLayoutRouteWithChildren,
}

const WarehouseRouteWithChildren = WarehouseRoute._addFileChildren(
  WarehouseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  UnauthorizedLazyRoute: UnauthorizedLazyRoute,
  OperationsRoute: OperationsRouteWithChildren,
  WarehouseRoute: WarehouseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
